all:
	xelatex dfm-kt-poster
	biber dfm-kt-poster
	xelatex dfm-kt-poster
	open dfm-kt-poster.pdf

ktm:
	xelatex ktm-poster
	biber ktm-poster
	xelatex ktm-poster
	open ktm-poster.pdf

clean:
	rm -f *.aux *.bbl *.bcf *.blg *.log *.out *.pdf *.xml
